Def file path
airplanedev/lib pull request #108
Opened 2022-04-19 20:10 UTC by leeweisberger

We want to know the absolute path to the defn file for git deploys.

2022-04-19 21:07 UTC, francescaleung requested changes

2022-04-19 21:07 UTC, francescaleung commented on pkg/deploy/discover/discover_test.go
> +			defnFilePath: "fixtures/defn.task.yaml",
these aren't absolute; should they be?

2022-04-19 22:45 UTC, leeweisberger commented on pkg/deploy/discover/discover_test.go
> +			defnFilePath: "fixtures/defn.task.yaml",
Woops yeah. Updated

2022-04-20 18:32 UTC, francescaleung approved these changes

2022-04-20 19:06 UTC, merged