Discover apps in addition to tasks
airplanedev/lib pull request #117
Opened 2022-04-26 19:55 UTC by leeweisberger

## Description
Update the discoverer to discover apps while it is discovering tasks.

An app can only be configured with a definition file that ends in `.app.yaml`.

## Test plan
I've tested this locally and it works e2e. Also have a unit test for discovering a simple app.

2022-04-26 19:56 UTC, leeweisberger commented on pkg/api/client.go
> +	GetApp(ctx context.Context, req GetAppRequest) (res App, err error)
This obviously will not work until I push this functionality on the server

2022-04-26 19:57 UTC, leeweisberger commented on pkg/deploy/discover/discover.go
> +func (d Discoverer) deduplicateAppConfigs(appConfigsBySlug map[string][]AppConfig) []AppConfig {
this is pretty much copy pasted from `deduplicateTaskConfigs`. Would be a great candidate for generics when we get go 18 working :exclamation:

2022-04-26 19:58 UTC, leeweisberger commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +func (d Definition_0_3) Marshal(format DefFormat) ([]byte, error) {
renamed from TaskDefFormat -> DefFormat so we can share this between tasks/apps

2022-05-02 18:42 UTC, stepzhou requested changes

2022-05-02 18:42 UTC, stepzhou commented on pkg/deploy/discover/discover_test.go
> +			name:  "app defn",
Nit: rename test function name to `TestDiscover`

2022-05-02 18:42 UTC, stepzhou commented on pkg/deploy/discover/discover.go
> +func (d Discoverer) deduplicateAppConfigs(appConfigsBySlug map[string][]AppConfig) []AppConfig {
This entire PR is mostly copy pasta code actually. This PR on top of the airport PR is really making me feel like we're missing some "buildable" interface here.

2022-05-02 18:42 UTC, stepzhou commented on pkg/deploy/discover/discover.go
> +	AppDiscoverers  []AppDiscoverer
Is there any way to have `TaskDiscoverer` and `AppDiscoverer` implement the same generic discoverer interface? They (including TaskConfig and AppConfig) are almost the same thing

2022-05-02 18:42 UTC, stepzhou commented on pkg/deploy/taskdir/definitions/definitions.go
> +	return GetTaskDefFormat(fn) != DefFormatUnknown
Nit: refactor out and call a more generic `GetDefFormat(fn, YamlTaskDefExtensions, JSONTaskDefExtensions) != DefFormatUnknown`

2022-05-03 22:28 UTC, leeweisberger commented on pkg/deploy/discover/discover.go
> +	AppDiscoverers  []AppDiscoverer
I could only do this if AppConfig and TaskConfig were combined into one, probably via an interface. In order to do this, all of the code downstream in the deploy code (both in cli and airport) would only have access to the returned interface. This interface would have to have all of the information needed by the downstream deploy code - currently a lot of task-specific things. So this interface would have to have fns for all of the task specific things and AppConfig would have to return nil for all of these. We could probably trim down on the number of task specific things needed for deploying, but currently there's a good amount of them.

I don't think that ^ is doable without a good amount of rework (pretty large refactor in 3 repos) and some interface functions that only apply to one or the other (task or app) which kind of defeats the purpose of the interface.

Another approach would be to make a bunch of these helper functions generic (e.g. deduplicateAppConfigs/deduplicateTaskConfigs) so that they work for both app configs and task configs as long as they satisfied a simple interface. I'd like to do that, but we aren't using go 1.18 so we don't have access to generics.

tl/dr I agree, but getting a common interface right now is a hefty refactor (I'd also probably want to wait until we add more fields to AppConfig) that we could put as a stretch goal for this project. Getting rid of some of the duplication with generics seems like an easier more incremental goal if we can get go 1.18 running.

Thoughts?

2022-05-04 18:48 UTC, leeweisberger commented on pkg/deploy/discover/discover.go
> +	AppDiscoverers  []AppDiscoverer
Using go 1.18 I updated deduplicateConfigs to be generic so it works for all discoverers

2022-05-05 16:09 UTC, stepzhou approved these changes

2022-05-05 16:09 UTC, stepzhou commented on pkg/deploy/discover/discover.go
> +	AppDiscoverers  []AppDiscoverer
> I don't think that ^ is doable without a good amount of rework (pretty large refactor in 3 repos) and some interface functions that only apply to one or the other (task or app) which kind of defeats the purpose of the interface.

If it's not straight-forward refactor, then it makes sense to me to defer this refactor. I'm more ok with how manual all this is since this is the first time we're adding a new buildable type. If we ever expect to add more buildable types though, we should probably reconsider the refactor

2022-05-05 20:59 UTC, merged