[WIP] Node code-only parser
airplanedev/lib pull request #180
Opened 2022-07-13 21:11 UTC by ameyakhare

## Description

## Test plan

2022-07-15 21:54 UTC, francescaleung reviewed
leaving comments here for now, I think I might benefit from a walkthrough &/ pointers to other relevant bits of code that this depends on.

Lots of comments here that aren't intended to be a "we should implement this" but rather a "is this a known limitation". Known limitations are fine as long as they're documented somewhere.

2022-07-15 21:54 UTC, francescaleung commented on pkg/deploy/discover/code_task_discover.go
> +			return nil, nil
Does this mean that code-only tasks still need to be created outside of this process? I can't just create a typescript file with arbitrary tasks & deploy it?

2022-07-15 21:54 UTC, francescaleung commented on pkg/deploy/discover/code_task_discover.go
> +	}
Is javascript not supported?

2022-07-15 21:54 UTC, francescaleung commented on pkg/deploy/discover/code_task_discover.go
> +	}
`npx` is a prerequisite for code-only node tasks? where is parser.ts coming from?

2022-07-15 21:54 UTC, francescaleung commented on pkg/build/node.go
> +	paramSlugs, _ := options["paramSlugs"].([]string)
you should have checks on the second return value here

2022-07-15 21:54 UTC, francescaleung commented on pkg/deploy/discover/code_task_discover.go
> +			})
no support for options/regex/required/default?

2022-07-21 18:57 UTC, ameyakhare commented on pkg/deploy/discover/code_task_discover.go
> +	}
javascript is supported now!

2022-07-21 18:58 UTC, ameyakhare commented on pkg/deploy/discover/code_task_discover.go
> +	}
npx is a prerequisite, but nothing else is. parser.ts is coming from an embedded string that is written to a temp file and executed

2022-07-21 18:58 UTC, ameyakhare commented on pkg/deploy/discover/code_task_discover.go
> +			})
we have support for all of those now

2022-07-21 19:47 UTC, colinking requested changes

2022-07-21 19:47 UTC, colinking commented on pkg/build/node-shim.js
> +import { {{.EntrypointFunc}} } from "{{.Entrypoint}}";
You can rename the import here, so you don't need to change the code below. It also avoids any issues with the entrypoint's name clashing with other variable definitions in this file.

```suggestion
import { {{.EntrypointFunc}} as task } from "{{.Entrypoint}}";
```

2022-07-21 19:47 UTC, colinking commented on pkg/build/node-shim.js
> +    let ret = await {{.EntrypointFunc}}._airplane.baseFunc(JSON.parse(process.argv[2]));
```suggestion
    let ret = await task._airplane.baseFunc(JSON.parse(process.argv[2]));
```

2022-07-21 19:47 UTC, colinking commented on pkg/build/node-shim.js
> +    let ret = await {{.EntrypointFunc}}._airplane.baseFunc(JSON.parse(process.argv[2]));
Minor: can we do double-underscores to match the convention of internal fields elsewhere? (e.g. `__airplaneType`).

```suggestion
    let ret = await {{.EntrypointFunc}}.__airplane.baseFunc(JSON.parse(process.argv[2]));
```

2022-07-21 19:47 UTC, colinking commented on pkg/build/node-shim.js
> +    {{if .IsCodeDefinedTask}}
You could drop this templating logic and instead check the type of `task` -- `if (task instanceof airplane.Task) {...}`. That should allow us to drop the `isCodeDefinedTask` field from the build options?

2022-07-21 19:47 UTC, colinking commented on pkg/build/node.go
> +	}
Why do we default this to `task`?

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +	// Run thing that extracts slug from something in the file.
Shouldn't this be checking if the file ends in `.tasks.[js|ts]`?

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +	}
Minor: could we do `.task.ts` and `.task.js`? Singular instead of plural. That lines up with the common case of a file having a single task.

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +	}
Add a defer statement to remove this file.

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +	var parsedTasks []map[string]interface{}
Let's replace the map with a proper struct definition.

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +			c.Logger.Warning(`Task with slug %s does not exist, skipping deployment.`, def.Slug)
Let's expose similar logic as the definition deployer to automatically deploy tasks that do not exist: https://github.com/airplanedev/lib/blob/25e800a19d255ef509e6ac9f2e06f3fa886c9e78/pkg/deploy/discover/defn_discover.go#L78-L98

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +		def.SetBuildConfig("paramSlugs", paramSlugs)
Is this new? What is it for?

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +	}
IIRC, we have similar logic elsewhere. Can we extract + share this?

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/parser/node/parser.ts
> +    parameters?: Record<string, ParamSchema>
Go does not retain key ordering when deserializing maps (but JS does). You might need to use [`ojson`](https://github.com/airplanedev/ojson)? Or serialize this as a list.

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/parser/node/parser.ts
> +class AirplaneParser {
Seems simpler to express this as a function rather than a class:

```ts
const extractTaskConfigs = (files: string[]): TaskConfig[] => {
  // ...
}
```

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/parser/node/parser.ts
> +            const lib = resolvedPath.replace(RegExp(".ts$"), "");
```suggestion
            const lib = resolvedPath.replace(/.ts$/, "");
```

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/parser/node/parser.ts
> +            let imports = require(`./${lib}`);
```suggestion
            const exports = require(`./${lib}`);
```

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/parser/node/parser.ts
> +            for (const itemName in imports) {
```suggestion
            for (const exportName in exports) {
```

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/parser/node/parser.ts
> +                const item = imports[itemName];
```suggestion
                const export = exports[exportName];
```

2022-07-21 19:47 UTC, colinking commented on pkg/deploy/discover/parser/node/parser.ts
> +                        if (typeof uParamSlug === "string") {
When would the slug not be a string?

2022-07-21 20:32 UTC, ameyakhare commented on pkg/deploy/discover/code_task_discover.go
> +			return nil, nil
will be done in a follow up (another task assigned to me) but as of now, yes

2022-07-21 20:43 UTC, ameyakhare commented on pkg/deploy/discover/parser/node/parser.ts
> +                        if (typeof uParamSlug === "string") {
oops meant to check uParamConfig not uParamSlug

2022-07-21 20:57 UTC, ameyakhare commented on pkg/build/node.go
> +	}
removed default, should work with default export and non-default export now

2022-07-21 20:58 UTC, ameyakhare commented on pkg/build/node-shim.js
> +    {{if .IsCodeDefinedTask}}
I just checked for .__airplane on the task until I land the node-sdk changes

2022-07-21 20:58 UTC, ameyakhare commented on pkg/build/node.go
> +	paramSlugs, _ := options["paramSlugs"].([]string)
no longer required

2022-07-21 21:33 UTC, colinking commented on pkg/build/node-shim.js
> +    {{if .IsCodeDefinedTask}}
Ah, nm about this. This only works if `airplane.Task` is a class. What you have now is fine!

2022-07-22 15:30 UTC, ameyakhare commented on pkg/deploy/discover/code_task_discover.go
> +		def.SetBuildConfig("paramSlugs", paramSlugs)
we don't need this anymore

2022-07-22 15:32 UTC, ameyakhare commented on pkg/deploy/discover/parser/node/parser.ts
> +class AirplaneParser {
yeah this is an artifact from when parsing was a little more complicated

2022-07-22 15:49 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +	}
FWIW, npx is installed automatically with npm/node nowadays. If you have node installed, you'll have npx, too.

2022-07-22 20:48 UTC, ameyakhare commented on pkg/deploy/discover/parser/node/parser.ts
> +    parameters?: Record<string, ParamSchema>
serialized as list to match definitions reference

2022-07-22 20:49 UTC, ameyakhare commented on pkg/deploy/discover/code_task_discover.go
> +	var parsedTasks []map[string]interface{}
im outputting json in the definitions reference format so we dont actually need to do any parsing ourselves 🎉

2022-07-25 18:51 UTC, colinking requested changes
LGTM apart from a question is about the `IsAirplaneTask` API

2022-07-25 18:51 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +					errorMsgs = append(errorMsgs, fmt.Sprintf("%s: %s", verr.Field(), verr.Description()))
🔥

2022-07-25 18:51 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +			}
Let's skip just the missing task, but continue with the other tasks that exist!

2022-07-25 18:51 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +				return nil, nil
Same here, let's continue to process the other tasks.

2022-07-25 18:51 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +			return nil, nil
Here, too.

2022-07-25 18:51 UTC, colinking commented on pkg/deploy/discover/code_task_discover.go
> +		metadata, err := c.Client.GetTaskMetadata(ctx, def.GetSlug())
nice

2022-07-25 18:51 UTC, colinking commented on pkg/deploy/discover/script_discover.go
> +	Workdir    string
Minor, these names are more clear IMO:

```suggestion
	AbsEntrypoint    string
	RelEntrypoint string
	RootDir   string
	WorkDir    string
```

2022-07-25 18:51 UTC, colinking commented on pkg/deploy/discover/script_discover.go
> +func taskPathMetadata(file string, kind build.TaskKind) (TaskPathMetadata, error) {
Extract from `discoverer/script_discoverer.go` to... `discoverer/path.ts`?

2022-07-25 18:51 UTC, colinking commented on pkg/deploy/discover/script_discover.go
> +	pathMetadata, err := taskPathMetadata(file, task.Kind)
Nice. Add to definition discoverer too: https://github.com/airplanedev/lib/blob/03140289bf0837d36d4ddf83420e969726118b88/pkg/deploy/discover/defn_discover.go#L121-L138

2022-07-25 20:33 UTC, ameyakhare commented on pkg/deploy/discover/code_task_discover.go
> +	return taskConfigs[0].Def.GetSlug(), nil
changed it to GetAirplaneTasks cause its returning a list and not a bool

2022-07-25 21:21 UTC, ameyakhare commented on pkg/deploy/discover/code_task_discover.go
> +		// Modify fields to add ones that are strictly required
I need to add the node: {entrypoint: foo, nodeVersion: foo} stanza anyways, so gonna skip this.

2022-07-25 21:26 UTC, ameyakhare commented on pkg/deploy/discover/code_task_discover.go
> +			"nodeVersion": "18",
I don't think you can leave it unset, the schema_0_3 requires it to be set. made a const on node.go in the build package

2022-07-26 18:58 UTC, colinking approved these changes

2022-07-26 19:40 UTC, merged