Allow resources to be a list
airplanedev/lib pull request #186
Opened 2022-07-19 15:07 UTC by francescaleung

## Description

Resource attachments can now be specified as a list, where each element is either a resource slug (where alias = slug) or an object with a single key (where key = alias, value = slug).

```
resources:
  - httpbin
  - db: demo_db
```

When running `airplane init`, resource attachments are preferred as a mapping of alias -> slug.

```
resources:
  httpbin: httpbin
  db: demo_db
```

## Test plan

Unit tests, tested manually.

2022-07-21 17:42 UTC, colinking requested changes
Looks good! Let's make the list of slugs the default serialization method when initing a task, so that aliases are not exposed unless a developer is using aliases.

Also, the list of objects is clever! Took me a second to grok what was happening. TBH, I'd prefer there weren't two identical ways to express aliased resources:

```yaml
resources:
  db: airplane_db
  api: airplane_api
```

```yaml
resources:
  - db: airplane_db
  - api: airplane_api
```

Can we remove this overlap by either dropping map support or dropping list-of-objects support?

2022-07-21 17:42 UTC, colinking commented on pkg/deploy/taskdir/definitions/schema_0_3.json
> +          "description": "[Experimental] A map of resources that can be accessed from your task. Keys are aliases, which determine how you refer to the resource in your task; values are existing reso
Can we remove the `[Experimental]` tag?

2022-07-21 17:42 UTC, colinking commented on pkg/deploy/taskdir/definitions/schema_0_3.json
> +          "description": "[Experimental] A map of resources that can be accessed from your task. Keys are aliases, which determine how you refer to the resource in your task; values are existing reso
IMO it's more clear to explain w/out aliases first:

```suggestion
          "description": "A list of resources to make available to your task. Resources are identified by slug, but can be mapped to an alias to configure how the task references the resource. If using aliases, resources are expressed as a map of alias to slug.",
```

2022-07-22 13:51 UTC, francescaleung commented
> Looks good! Let's make the list of slugs the default serialization method when initing a task, so that aliases are not exposed unless a developer is using aliases.
> 
> Also, the list of objects is clever! Took me a second to grok what was happening. TBH, I'd prefer there weren't two identical ways to express aliased resources:
> 
> ```yaml
> resources:
>   db: airplane_db
>   api: airplane_api
> ```
> 
> ```yaml
> resources:
>   - db: airplane_db
>   - api: airplane_api
> ```
> 
> Can we remove this overlap by either dropping map support or dropping list-of-objects support?

Pretty sure we talked about list-of-objects a month or so ago, ha. Does it matter that we support both? I would prefer to drop list-of-objects because we already support map & I don't want to remove that.

2022-07-22 13:55 UTC, francescaleung commented on pkg/deploy/taskdir/definitions/schema_0_3.json
> +          "description": "[Experimental] A map of resources that can be accessed from your task. Keys are aliases, which determine how you refer to the resource in your task; values are existing reso
`[Experimental]` is because resource attachment never got officially released--the flag is still on in prod that prevents people from seeing the resource attachment UI. It's tagged as `[Experimental]` because this schema file is the one that feeds the intellisense in y'all's fancy code editors as long as it's in main.

It never got officially released because there's not much of a point in attaching resources if you can't actually use them (documentation, but mostly was waiting on SDK).

2022-07-22 15:34 UTC, colinking commented
> Pretty sure we talked about list-of-objects a month or so ago, ha. Does it matter that we support both? I would prefer to drop list-of-objects because we already support map & I don't want to remove that.

Dropping lists-of-objects sgtm!

2022-07-22 15:40 UTC, colinking requested changes
Requesting changes about the experimental tag + dropping list-of-objects

2022-07-22 20:53 UTC, colinking approved these changes

2022-07-22 20:58 UTC, merged