Respect existing package.json packages on build
airplanedev/lib pull request #193
Opened 2022-07-21 19:03 UTC by zhan-airplane

## Description
Didn't realize `yarn add` would put in the latest version even if it already exists in the `package.json`, so this handles that case

Not sure if there's a better way to detect this other than installing and using `jq`, open to suggestions

## Test plan
Ran locally

---
cc @stepzhou @rose-huang

2022-07-22 10:02 UTC, leeweisberger requested changes

2022-07-22 10:02 UTC, leeweisberger commented on pkg/build/view.go
> +		RUN [ $(jq .dependencies.\"@airplane/views\" package.json) != 'null' ] || yarn add @airplane/views
This is going to run these `yarn add` in serial right? We want to run them in parallel.

Rather than using jq - how about doing this in Go code above. Grab the package.json and convert it to a struct (we do this in lib in a few places). Decide which packages we need to install. Insert them into this template using a go template string `RUN yarn add {{.packagesToAdd}}` (although we can skip if packagestoadd is empty

2022-07-22 10:09 UTC, zhan-airplane commented on pkg/build/view.go
> +		RUN [ $(jq .dependencies.\"@airplane/views\" package.json) != 'null' ] || yarn add @airplane/views
Ah yeah that's a good idea I'll do that instead, somehow forgot I could write it in go oops haha

2022-07-22 10:56 UTC, leeweisberger approved these changes

2022-07-22 10:56 UTC, leeweisberger commented on pkg/build/view.go
> +	deps, ok := packageJSON.(map[string]interface{})["dependencies"].(map[string]interface{})
Check dev dependencies too. the vite stuff might very well be in devdependencies

2022-07-22 10:56 UTC, leeweisberger commented on pkg/build/view.go
> +		{{end}}
Rather than doing an add and then an install, it would be more performant to add the dependencies to the package.json and then run the install command. This would change from 2 installs to 1. Would pretty pretty easy - just add to the dependency list and then you can remove this line. I'll leave it up to you if you want to do this now

2022-07-22 10:56 UTC, leeweisberger commented on pkg/build/view.go
> +		PackagesToAdd    string
While you're here, can you update the InstallCommand to clean the cache. a'la https://github.com/airplanedev/lib/pull/188/files

2022-07-25 20:53 UTC, zhan-airplane commented
@leeweisberger actually while messing with this I have a question about `--frozen-lockfile` - if we're manually editing the `package.json`, `--frozen-lockfile`'s always going to fail right..?

2022-07-25 20:54 UTC, zhan-airplane commented
Is it ok to get rid of it? Not too sure what the best practice would be here

2022-07-26 15:09 UTC, merged