Support deploying views with code configuration
airplanedev/lib pull request #213
Opened 2022-08-04 22:47 UTC by ameyakhare

Resolves AIR-4417
Resolves AIR-4416

## Description
Adds support for deploying views with code configuration. Users need to export default airplane.view(config, component) instead of default exporting the component itself.

## Test plan
Deploys properly to stage.

2022-08-10 00:25 UTC, leeweisberger requested changes
Will look when we have a test suite. We should be able to write some fixtures and ensure that we are discovering the task correctly pretty easy.

2022-08-10 19:28 UTC, leeweisberger reviewed
Leaving a few comments - going to finish reviewing in a few....

2022-08-10 19:28 UTC, leeweisberger commented on pkg/deploy/discover/build.go
> +// "main": "index.dummy.js" to allow the library to resolve properly when importing
Can you add some more description for those that don't know what index.dummy.js is

2022-08-10 19:28 UTC, leeweisberger commented on pkg/deploy/discover/code_task_discover.go
> +	}()
Where is the .airplane dir being created?

2022-08-10 19:28 UTC, leeweisberger commented on pkg/deploy/discover/code_view_discover.go
> +	if err := esbuildUserFiles(pm.RootDir); err != nil {
How fast or slow is this? Wondering because we are doing it for every file and we are doing it twice, once for tasks and once for views right?

2022-08-10 19:28 UTC, leeweisberger commented on pkg/deploy/discover/code_view_discover.go
> +	parsedConfigs.ViewConfigs[0]["entrypoint"] = pm.AbsEntrypoint
Shouldn't each of these be typed? Is it an untyped map?

2022-08-10 19:28 UTC, leeweisberger commented on pkg/deploy/discover/code_view_discover.go
> +	for _, suffix := range []string{".view.tsx", ".view.jsx", ".view.ts", ".view.js"} {
Why are you checking for .ts and .js files?

2022-08-10 21:55 UTC, leeweisberger requested changes
Just have some qs. Will approve when resolved. Nothing major

2022-08-10 21:55 UTC, leeweisberger commented on pkg/deploy/discover/discover.go
> +			}
Why do we need this when you added .airplane to ignoredDirectories

2022-08-10 21:55 UTC, leeweisberger commented on pkg/deploy/discover/parser/node/parser.ts
> +          })
nit: viewConfigs.push

2022-08-10 21:55 UTC, leeweisberger commented on pkg/deploy/discover/parser/node/parser.ts
> +          taskConfigs = taskConfigs.concat({
push?

2022-08-10 21:55 UTC, leeweisberger commented on pkg/deploy/discover/fixtures/view/codeOnly.view.tsx
> +}
Is this how someone specifies a view? What about their source code? They export that but not as default?

2022-08-10 21:55 UTC, leeweisberger commented on pkg/deploy/discover/fixtures/view/codeOnly.view.tsx
> +}
How do we know what the entrypoint component is?

2022-08-11 17:50 UTC, ameyakhare commented on pkg/deploy/discover/code_task_discover.go
> +	}()
in the root directory of the project

2022-08-11 17:52 UTC, ameyakhare commented on pkg/deploy/discover/code_view_discover.go
> +	if err := esbuildUserFiles(pm.RootDir); err != nil {
decently slow but can be faster if all files parsed at once

2022-08-11 18:01 UTC, ameyakhare commented on pkg/deploy/discover/fixtures/view/codeOnly.view.tsx
> +}
this is how you define it, but I emulated what the lib did so that we don't have to install it. export default airplane.view({slug:"foo"}, Component);

2022-08-11 18:01 UTC, leeweisberger approved these changes

2022-08-11 18:31 UTC, ameyakhare commented on pkg/deploy/discover/discover.go
> +			}
fixed

2022-08-11 18:34 UTC, ameyakhare commented on pkg/deploy/discover/code_view_discover.go
> +	parsedConfigs.ViewConfigs[0]["entrypoint"] = pm.AbsEntrypoint
we need to add a field (entrypoint) then validate.

2022-08-11 19:02 UTC, merged