Add utility to generate inline code config js/ts tasks
airplanedev/lib pull request #256
Opened 2022-09-02 20:24 UTC by ameyakhare

## Description
Adds GenerateInline function that will generate an inline configured js/ts task definition. Added it to the runtime interface, so the implementation for the other languages is TBD.

## Test plan
Generated a file for this task: https://web.airstage.app/tasks/tsk20220701zjfvvatnlei?__env=prod
Output:
```
import airplane from "airplane"

export default airplane.task(
  {
	slug: "node_builtins_demo",
	name: "Node Builtins Demo",
	description: "This is a description.",
	parameters: {
	  example_parameter: {
	    type: "shorttext",
	    name: "Example Parameter",
	    description: "This is an example parameter.",
	  	default: "foobar",
		options: [
		  "foobar",
		  {label: "notegsdee", value: "eggsdee"},
		]
	  },
	},
	allowSelfApprovals: false,
	timeout: 3500,
	constraints: {
	  mta: "v2",
	},
	resources: {
	  db: "db",
	  mail: "res_airplane_dev",
	  website: "praygo",
	},
	nodeVersion: "16",
	envVars: {
	  CONFIG_ENV_VAR: {
	    config: "AIRPLANE_DATA_PLANE_BUCKET"
	  },
	  VALUE_ENV_VAR: "prayge",
	},
  },
  (params) => {
	// Put the main logic of the task in this function.
	console.log('parameters:', params);

	// You can return data to show outputs to users.
	// Outputs documentation: https://docs.airplane.dev/tasks/outputs
	return [
		{element: 'hydrogen', weight: 1.008},
		{element: 'helium', weight: 4.0026},
	];
  }
)
```

2022-09-02 21:00 UTC, francescaleung requested changes

2022-09-06 16:17 UTC, ameyakhare commented on pkg/runtime/javascript/javascript.go
> +    name: "{{.}}",
added!

2022-09-07 14:36 UTC, francescaleung approved these changes

2022-09-07 14:36 UTC, francescaleung commented on pkg/runtime/javascript/javascript.go
> +	return s
hmmm you almost want this to be json.Marshal without the first + last quotes. is that too much?

2022-09-07 18:00 UTC, ameyakhare commented on pkg/runtime/javascript/javascript.go
> +	return s
I used json marshal now

2022-09-07 18:06 UTC, merged