Surface better error for malformed python tasks
airplanedev/lib pull request #275
Opened 2022-09-12 14:19 UTC by ericliuche

## Description
Surface a better error if a user is missing a `main` function or if the `main` function is malformed

## Test plan
ran locally, tested task with no params 

<img width="1260" alt="Screen Shot 2022-09-13 at 1 48 21 PM" src="https://user-images.githubusercontent.com/11494140/189974157-989a779c-5d56-43b5-91fb-60c211ea1d2e.png">
<img width="1260" alt="Screen Shot 2022-09-13 at 1 48 33 PM" src="https://user-images.githubusercontent.com/11494140/189974187-700d6e0d-89ff-4814-ba88-f7da78899064.png">

2022-09-12 15:00 UTC, colinking requested changes

2022-09-12 15:00 UTC, colinking commented on pkg/build/python-shim.py
> +            raise Exception(f"""`main` function must have exactly 1 parameter, found {num_params}. Update the main method like so and re-deploy:
Do we not handle this? Because we should. If a task takes no parameters, you shouldn't need to define the `params` argument. This is how it works for Node.

So bit of scope-creep, but that should be a quick fix -- could you do that here?

2022-09-12 15:00 UTC, colinking commented on pkg/build/python-shim.py
> +            raise Exception("""Task is missing a `main` function. Add a main method like so and re-deploy:
nice

2022-09-12 15:00 UTC, colinking commented on pkg/build/python-shim.py
> +        if not hasattr(mod, "main"):
This breaks with `"mod.{{.EntrypointFunc}}"` right?

2022-09-12 15:00 UTC, colinking commented on pkg/build/python-shim.py
> +            raise Exception("""Task is missing a `main` function. Add a main method like so and re-deploy:
Does Python call them methods or functions? Let's be consistent.

```suggestion
            raise Exception("""Task is missing a `main` method. Add the following to your task and re-deploy:
```

2022-09-12 15:00 UTC, ericliuche commented on pkg/build/python-shim.py
> +            raise Exception(f"""`main` function must have exactly 1 parameter, found {num_params}. Update the main method like so and re-deploy:
yup ill toss that in here

2022-09-12 15:01 UTC, ericliuche commented on pkg/build/python-shim.py
> +        if not hasattr(mod, "main"):
yeah, but that's changing very soon when i add my inline code changes so ill just update it then

2022-09-12 15:05 UTC, colinking commented on pkg/build/python-shim.py
> +        if not hasattr(mod, "main"):
Any reason not to do it now? Since the shim already has inline config logic in it, I'd like to stay consistent with that.

2022-09-12 15:07 UTC, ericliuche commented on pkg/build/python-shim.py
> +        if not hasattr(mod, "main"):
making the change right now would break the current behavior, we need to first agree on the sdk change and then update the logic here. basically the semantics of how we're calling the user's inline code is changing from

`mod.{{.EntrypointFunc}}.base_func(json.loads(args[1]))`

to something like

`mod.{{.EntrypointFunc}}(**json.loads(args[1]))`

2022-09-12 15:07 UTC, ericliuche commented on pkg/build/python-shim.py
> +            raise Exception(f"""`main` function must have exactly 1 parameter, found {num_params}. Update the main method like so and re-deploy:
ah @colinking, this doesn't work for node either... 

https://web.airstage.app/runs/run20220912z0m7sp6grw7?__env=prod

2022-09-12 15:12 UTC, ericliuche commented on pkg/build/python-shim.py
> +            raise Exception(f"""`main` function must have exactly 1 parameter, found {num_params}. Update the main method like so and re-deploy:
nvm nvm that was my bad, it does work

2022-09-13 18:10 UTC, colinking approved these changes

2022-09-13 18:10 UTC, colinking commented on pkg/build/python-shim.py
> +        if not arg_dict:
This is checking if any args were passed to the task, not whether the task has any parameters.

Consider a task with a single optional parameter. If you don't pass a value, does this still work?

IOW, we should support the following:

- `main(params)` w/ `{}` -> kk
- `main()` w/ `{}` -> kk
- `main(params)` w/ `{"foo": "bar"}` -> kk
- `main()` w/ `{"foo": "bar"}` -> should error

2022-09-13 18:15 UTC, ericliuche commented on pkg/build/python-shim.py
> +        if not arg_dict:
right now all the cases you listed are correct. with the single option parameter, if no value is passed both `main(params)` and `main()` work. but if a parameter is provided, only `main(params)` works

2022-09-13 21:53 UTC, merged