Add build options for preinstall/postinstall scripts
airplanedev/lib pull request #288
Opened 2022-09-15 12:42 UTC by ericliuche

## Description
Adds support for users to provide `airplane_postinstall.sh and `airplane_preinstall.sh` scripts to execute hooks in our build process. We look for these scripts in the user's tasks root directory. For node tasks, if users provide both a command in `airplane_postinstall.sh` and in their package.json, we use the latter.

## Test plan
added unit tests, ran locally with build hooks and verified they were being executed

2022-09-15 23:20 UTC, colinking requested changes

2022-09-15 23:20 UTC, colinking commented on pkg/examples/typescript/custompostinstall/yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
This is missing in the `installhooks` example.

2022-09-15 23:20 UTC, colinking commented on pkg/build/python_test.go
> +			Root: "python/buildoptions",
rename this example too

2022-09-15 23:20 UTC, colinking commented on pkg/build/node_test.go
> +			Root: "typescript/buildoptions",
Let's make these examples consistent. Rename example to `installhooksviashell` and the other to `installhooksviapackagejson`?

2022-09-15 23:20 UTC, colinking commented on pkg/build/python_test.go
> +			SearchString: "[1]",
Does this actually test preinstalling? It's looking for "[1]".

The postinstall example before would fail because `prettier` wouldn't get installed otherwise.

2022-09-15 23:20 UTC, colinking commented on pkg/build/options.go
> +	preInstallPath := filepath.Join(root, preInstallScriptName)
Look for these scripts in every directory from the entrypoint's directory up to the root directory. Pick the one closest to the entrypoint. You can use our `fsx.Find` for this.

2022-09-15 23:20 UTC, colinking commented on pkg/build/node_test.go
> +			},
Same concern as the Python task -- this isn't actually testing that preinstall is running.

2022-09-15 23:20 UTC, colinking commented on pkg/build/node.go
> +		RUN {{.PreInstallCommand}}
This should execute the script itself, not the contents. Scripts will span multiple lines and include comments that won't work if you inline them into a `RUN` command. Hashbangs should also work.

Seems like you'll need to support both this + executing content directly for `package.json` commands.

2022-09-15 23:20 UTC, colinking commented on pkg/build/node.go
> +	buildOptions BuildOptions,
This API is confusing to me, e.g. what is the diff between options/args/buildOptions? Can you clean it up?

2022-09-15 23:25 UTC, colinking commented on pkg/build/options.go
> +	preInstallPath := filepath.Join(root, preInstallScriptName)
Whoops, use `fsx.FindUntil` actually: https://github.com/airplanedev/lib/blob/b95ed2a190dd783650545f0476fdaf44ec857d66/pkg/utils/fsx/fsx.go#L61

2022-09-16 14:04 UTC, ericliuche commented on pkg/build/python_test.go
> +			SearchString: "[1]",
Fixed so that the install hooks write files. The tasks read in the files and print their contents and we check the string is there

2022-09-16 14:04 UTC, ericliuche commented on pkg/build/options.go
> +	preInstallPath := filepath.Join(root, preInstallScriptName)
Done!

2022-09-16 14:04 UTC, ericliuche commented on pkg/build/node.go
> +		RUN {{.PreInstallCommand}}
fixed

2022-09-16 14:05 UTC, ericliuche commented on pkg/build/node.go
> +	buildOptions BuildOptions,
since we now need the task's entrypoint, moved the install hook login inside the `build/node.go` and `build/python.go` files.

2022-09-16 15:40 UTC, colinking approved these changes
Thanks! LGTM.

2022-09-16 15:40 UTC, colinking commented on pkg/build/install_hooks.go
> +type InstallHooks struct {
Can this be unexported? In general, we should not export fields whenever we can, as it keeps the API surface area smaller.

2022-09-16 15:40 UTC, colinking commented on pkg/build/install_hooks.go
> +			filepath.Join(root, filepath.Dir(entrypoint)),
Can `entrypoint` ever be a directory? If so, keep this in mind: https://github.com/airplanedev/cli/pull/659/files#diff-54c597b320ae143c8edd1055c0fb6d644d5e7e9031f790c373744f4bbdd155b4R85

2022-09-16 15:40 UTC, colinking commented on pkg/build/install_hooks.go
> +			filepath.Dir(root),
Same goes with `root`, though we may `filepath.Clean` this always in which case it's not an issue.

2022-09-16 15:40 UTC, colinking commented on pkg/build/install_hooks.go
> +		if start, found := fsx.FindUntil(
More idiomatic

```suggestion
		if dir, ok := fsx.FindUntil(
```

2022-09-16 15:40 UTC, colinking commented on pkg/build/install_hooks.go
> +			return relpath, err
```suggestion
			return relpath, nil
```

2022-09-16 15:40 UTC, colinking commented on pkg/build/install_hooks.go
> +		); found {
It's idiomatic to keep the happy path unindented, and put error handling / sad path handling in these if clauses. 

```suggestion
		); !ok {
```

2022-09-16 15:40 UTC, colinking commented on pkg/build/node.go
> +	installHooks, err := GetInstallHooks(entrypoint, root)
Minor, but should we just call these `hooks`? Since we might expose non-install hooks in the future.

Not important, since this is guessing about the future, but up to you.

2022-09-16 15:40 UTC, colinking commented on pkg/build/node.go
> +		RUN ./airplane_preinstall.sh
This creates two layers. Let's merge:

```
RUN chmod +x airplane_preinstall.sh && ./airplane_preinstall.sh
```

2022-09-16 15:40 UTC, colinking commented on pkg/build/node.go
> +		RUN ./airplane_postinstall.sh
same here

2022-09-16 17:06 UTC, ericliuche commented on pkg/build/install_hooks.go
> +			filepath.Join(root, filepath.Dir(entrypoint)),
realized we can just always assume entrypoint is a directory and it also works for a file, so just going to remove the Dir call

2022-09-16 18:09 UTC, merged