Load envSlug from get param in main.tsx if it exists
airplanedev/lib pull request #304
Opened 2022-09-26 18:16 UTC by zhan-airplane

## Description
Otherwise if someone promotes a view between environments, we don't have a way of indicating to the view that the env is updated (since the env slug is baked into the view)

## Test plan
Ran locally

---
cc @stepzhou @rose-huang @geodn

2022-09-26 20:59 UTC, leeweisberger requested changes

2022-09-26 20:59 UTC, leeweisberger commented on pkg/build/views/main.tsx
> +const paramsEnvSlug = (document) ? (new URL(document.location)).searchParams.get("envSlug") : null;
```suggestion
const paramsEnvSlug = typeof window !== 'undefined' ? (new URL(document.location)).searchParams.get("envSlug") : null;
```

2022-09-26 20:59 UTC, leeweisberger commented on pkg/build/views/main.tsx
> +const paramsEnvSlug = (document) ? (new URL(document.location)).searchParams.get("envSlug") : null;
I don't think this is going to work in an iframe. I think you can test this in the editor where we are also rendering the view in an iframe. I **think** this is going to return to the location of the iframe which is different than the location in the parent browser.

Let me know if you test this and I'm wrong, but I'm pretty sure it won't work.

We are passing in the query params as url fragments. See the attached photo. I believe that's the url you're gonna get with window.location

![image](https://user-images.githubusercontent.com/6363419/192379015-a03f0350-8bdb-4a21-a802-2f702d2448fa.png)

You can read in the env using the fragment. But this also has to work if this isn't in an iframe. See lib/src/routing/useRouter.ts in views for how we grab the search params regardless of whether the view is in an iframe.

2022-09-26 21:03 UTC, leeweisberger commented on pkg/build/views/main.tsx
> +const paramsEnvSlug = (document) ? (new URL(document.location)).searchParams.get("envSlug") : null;
^ that is safe in a non-web environment

2022-09-26 21:03 UTC, leeweisberger commented on pkg/build/views/main.tsx
> +const paramsEnvSlug = (document) ? (new URL(document.location)).searchParams.get("envSlug") : null;
I saw your other pr. Ok now I get why this works when you tested it :)

2022-09-26 21:03 UTC, leeweisberger approved these changes

2022-09-27 06:51 UTC, zhan-airplane commented on pkg/build/views/main.tsx
> +const paramsEnvSlug = (document) ? (new URL(document.location)).searchParams.get("envSlug") : null;
Yeah haha I *do* want the iframe location, not the parent browser location

2022-09-27 06:57 UTC, zhan-airplane commented
BTW gonna change from `envSlug` to `__env` just for consistency with other parts of web code

2022-09-27 07:06 UTC, merged