Use workflow shims from SDK
airplanedev/lib pull request #334
Opened 2022-10-07 03:14 UTC by yolken-airplane

## Description
This change updates the workflow shims in lib to use the SDK-provided interceptors and worker code added in https://github.com/airplanedev/js-sdk/pull/159. Note that this will break workflow builds if users are using older SDK versions, so before rolling this out we'll need to bump the SDK version and do some sort of version check here.

cc: @calufornia 

## Test plan
Testing completed successfully via deploying and running some tasks with the updated SDK code locally.

2022-10-11 18:36 UTC, colinking requested changes
LGTM, but let's add that version check before merging this. Let's make sure the error is nice and clear about how the user just needs to upgrade their SDK version.

2022-10-11 18:36 UTC, colinking commented on pkg/build/workflow/worker-shim.js
>  async function main() {
Do we need to the `JSON.parse` logic? I wouldn't expect parameters to get passed into the worker.

2022-10-12 00:44 UTC, yolken-airplane commented on pkg/build/workflow/worker-shim.js
>  async function main() {
Yeah, they're actually used. Will remove them...

2022-10-12 02:49 UTC, yolken-airplane commented
> LGTM, but let's add that version check before merging this. Let's make sure the error is nice and clear about how the user just needs to upgrade their SDK version.

Yup, will add that after my other change has been merged and I've bumped up the SDK version there.

2022-10-12 02:49 UTC, yolken-airplane commented on pkg/build/workflow/worker-shim.js
>  async function main() {
Done.

2022-10-12 20:08 UTC, colinking approved these changes

2022-10-12 20:08 UTC, colinking commented on pkg/build/node.go
> +			meetsMin, err := meetsMinimumVersion(apVersion, minWorkflowSDKVersion)
Hmm, I'm now realizing both this and the `workflowRuntimePkg` logic below are incorrect. The version we get from a `package.json` will be a range. We want the exact version used, which we would need to get from the lockfile.

For example, I might have a task with `airplane: ^0.2.3`. If I ran `npm install` when `0.2.4` was the latest version, then the lockfile will specify `0.2.4`. If I run `npm ci` (like our builder does), it'll install `0.2.4` even though `0.2.10` is the latest acceptable version by semver range. That means (1) the `meetsMinimumVersion` won't work and (2) the shim will have a different version of the workflow runtime since the shim copies the range but not the lockfile.

The proper behavior would be to extract the `airplane` version from the lockfile (falling back on the `package.json` version if there is no lockfile... though that may be unnecessary, since I think `npm ci`/`yarn install --frozen-lockfile` fail if there is no lockfile) and use that.

2022-10-12 20:08 UTC, colinking commented on pkg/build/node.go
> +			meetsMin, err := meetsMinimumVersion(apVersion, minWorkflowSDKVersion)
Looks like you can get this version using the npm/yarn CLIs:

```
yarn list --pattern airplane --silent --json --no-progress | jq -r '.data.trees[0].name'
cat package-lock.json | jq -r '.packages["node_modules/airplane"].version'
```

2022-10-12 20:08 UTC, colinking commented on pkg/build/node.go
> +			meetsMin, err := meetsMinimumVersion(apVersion, minWorkflowSDKVersion)
Hmm, judging by your `meetsMinimumVersion`, you're ignoring the `^/~` entirely s.t. `^0.2.3` will still error. That works, though it could have false positives. Maybe that's acceptable? Your call. If we change this now, it'll also benefit the `workflowRuntimePkg` logic :)

2022-10-12 22:13 UTC, yolken-airplane commented on pkg/build/node.go
> +			meetsMin, err := meetsMinimumVersion(apVersion, minWorkflowSDKVersion)
Yeah, I was trying to take an approach that was overly conservative (but not 100% correct). 

I've attempted to fix this by getting the version via yarn or `package-lock.json`; if a version isn't found there, we just fall back to the version from the deps. Does this seem ok to you?

2022-10-12 22:16 UTC, yolken-airplane commented on pkg/build/node.go
> +	defaultSDKVersion     = "0.2.10"
Done.

2022-10-12 22:16 UTC, yolken-airplane commented on pkg/build/node.go
> +						"The airplane SDK version in your bundle (%s) does not meet the minimum required one for workflow tasks (%s). Please update the version of your airplane dependency.",
Fixed.

2022-10-12 23:24 UTC, colinking approved these changes
This is fantastic. Thanks!!

2022-10-12 23:24 UTC, colinking commented on pkg/build/node_externals.go
> +		return "", errors.Errorf("No version found for package %s", packageName)
nit: lowercase, for wrapping

```suggestion
		return "", errors.Errorf("no version found for package %s", packageName)
```

2022-10-12 23:24 UTC, colinking commented on pkg/build/node_externals.go
> +			"Found %s version via yarn: %s\n",
I generally try to use `%q` since it is more clear within sentences and handles empty strings

```suggestion
			"Found %q version via yarn: %q\n",
```

2022-10-12 23:24 UTC, colinking commented on pkg/build/node_externals.go
> +	)
These should be debug logs if anything. We don't want a user to see them in their build logs and think they did something wrong.

2022-10-12 23:32 UTC, yolken-airplane commented on pkg/build/node_externals.go
> +	)
They're actually completely hidden from users due to the logic in https://github.com/airplanedev/airport/blob/main/pkg/builder/builder.go#L671.

2022-10-12 23:37 UTC, yolken-airplane commented on pkg/build/node_externals.go
> +	)
Yeah, actually, that makes sense given the code- anything that we log out outside of buildkit will be hidden by default unless it has the magical build log prefix.

2022-10-12 23:44 UTC, yolken-airplane commented on pkg/build/node_externals.go
> +		return "", errors.Errorf("No version found for package %s", packageName)
Fixed. So we never want to use upper-case for the first letter of an error message? I was wondering what the correct standard was there. :-)

2022-10-12 23:44 UTC, yolken-airplane commented on pkg/build/node_externals.go
> +			"Found %s version via yarn: %s\n",
Oh, didn't know about that. Fixed!

2022-10-12 23:45 UTC, colinking commented on pkg/build/node_externals.go
> +		return "", errors.Errorf("No version found for package %s", packageName)
We should lint for it, but yeah -- lowercase always and optionally add logic to uppercase the first char when printing error messages. This is how it works in our API!

2022-10-12 23:58 UTC, merged