Add bundle build dockerfile generation
airplanedev/lib pull request #362
Opened 2022-10-25 18:21 UTC by ameyakhare

## Description
Adds a unique dockerfile for generating an image from a bundle build.

## Test plan
Works locally.

2022-10-25 21:47 UTC, leeweisberger requested changes

2022-10-25 21:47 UTC, leeweisberger commented on pkg/build/builder.go
> +	case NodeBuildType:
Going to add other types after?

2022-10-25 21:47 UTC, leeweisberger commented on pkg/build/node.go
> +// node creates a dockerfile for Node (typescript/javascript).
Use the correct function name. What's the diff between this and the node function?

2022-10-25 21:47 UTC, leeweisberger commented on pkg/build/node.go
> +	argsCommand := strings.Join(buildArgs, "\n")
Split this into a helper and reuse

2022-10-25 21:47 UTC, leeweisberger commented on pkg/build/node.go
> +		}
Split into a helper and reuse

2022-10-25 21:47 UTC, leeweisberger commented on pkg/build/node.go
> +	// TODO: install hooks per root directory
What does this mean? You're doing install hooks below. What are we missinig?

2022-10-25 21:47 UTC, leeweisberger commented on pkg/build/node.go
> +	cfg.InstallCommand = strings.ReplaceAll(installCommand, "\n", "\\n")
break this into a helper

2022-10-25 21:47 UTC, leeweisberger commented on pkg/build/node.go
> +				--outfile=/airplane/.airplane/dist/universal-shim.js
You should just build this once and then just copy it into the image. We don't need to build this for every single task that is deployed.

2022-10-25 21:47 UTC, leeweisberger commented on pkg/build/node.go
> +		RUN node /airplane/.airplane/inlineParser.js {{.DiscoverFilesList}}
How are we going to get this out of the image?

2022-10-25 21:47 UTC, leeweisberger commented on pkg/build/node.go
> +	DiscoverFilesList                string
Can you add comments what these are? There's a loooota stuffs here

2022-10-25 21:47 UTC, leeweisberger commented on pkg/build/node.go
> +				--outfile=/airplane/.airplane/dist/universal-shim.js
We can do as a followup, but there's no reason to do this every time. We can just add a build script next to the shim that produces the built js file.

2022-10-26 17:52 UTC, ameyakhare commented on pkg/build/builder.go
> +	case NodeBuildType:
yep, thats the plan

2022-10-26 18:30 UTC, ameyakhare commented on pkg/build/node.go
> +	// TODO: install hooks per root directory
I fixed this. basically, we're only going to look for a pre/post path in the task root for bundle builds

2022-10-26 18:44 UTC, ameyakhare commented on pkg/build/node.go
> +		RUN node /airplane/.airplane/inlineParser.js {{.DiscoverFilesList}}
follow up, not doing it right now

2022-10-26 21:18 UTC, leeweisberger requested changes
re-request after tests plz

2022-10-27 23:08 UTC, leeweisberger approved these changes

2022-10-27 23:08 UTC, leeweisberger commented on pkg/build/node.go
> +	// string of space-separated built js files to discover entity configs from
```suggestion
	// FilesToDiscover represents the built JS files to discover entity configs from. These built files are the output of esbuild.
```

2022-10-27 23:08 UTC, leeweisberger commented on pkg/build/node.go
> +		RUN node /airplane/.airplane-build-tools/inlineParser.js {{.FilesToDiscover}}
```suggestion
                # Discover inline tasks now that dependencies are installed and tasks are built.
                # FilesToDiscover should be the location where esbuild outputs transpiled JS files.
		RUN node /airplane/.airplane-build-tools/inlineParser.js {{.FilesToDiscover}}
```

2022-10-28 15:05 UTC, merged