Airplane config
airplanedev/lib pull request #366
Opened 2022-10-27 00:18 UTC by leeweisberger

## Description
Create airplane config yaml. 

Currently the airplane config only contains the node version and env vars.

The node version is read in when determining the node version (superseded by package.json).

So far nobody reads env vars. We are going to read these during dev and in the server during build. I'll add this functionality as follow ups.

This is undocumented, so this should be a no-op.

## Test plan
Unit tests

2022-10-27 19:50 UTC, ameyakhare requested changes
one open question, everything else looks fine

2022-10-27 19:50 UTC, ameyakhare commented on pkg/deploy/config/config.go
> +	EnvVars     api.TaskEnv            `yaml:"envVars,omitempty"`
are these task env vars or build env vars? I feel like we should make the distinction that this is a buildenv var and task env vars should be passed in using the task config

2022-10-28 00:01 UTC, leeweisberger commented on pkg/deploy/config/config.go
> +	EnvVars     api.TaskEnv            `yaml:"envVars,omitempty"`
I'm thinking they're both.
- We want to support build time env vars because those just won't work for inline tasks.
- It's also nice to support task env vars because this gives us a place to share env vars across many tasks. e.g. if all of our tasks uses `AIRPLANE_API` I can set it once here instead of on every individual task.

So we document that runtime env vars can optionally go here to share them amongst many tasks. Build time env vars have to go here.

Thoughts? too confusing? We could split them up, but I don't see a great reason to...

2022-10-28 17:38 UTC, ameyakhare commented on pkg/deploy/config/config.go
> +	EnvVars     api.TaskEnv            `yaml:"envVars,omitempty"`
I actually think we should split them up, since for environments, the idea is that those build env vars cannot be environment-specific

2022-10-28 17:39 UTC, ameyakhare commented on pkg/deploy/config/config.go
> +	EnvVars     api.TaskEnv            `yaml:"envVars,omitempty"`
not going to hard block on this, but its a little weird that build env vars and runtime env vars are lumped together when they really shouldnt need to be the same

2022-10-28 17:39 UTC, ameyakhare approved these changes

2022-10-28 20:15 UTC, leeweisberger commented on pkg/deploy/config/config.go
> +	EnvVars     api.TaskEnv            `yaml:"envVars,omitempty"`
I'm going to merge for now, but let's discuss. This isn't going to be shipped for a bit.

2022-10-28 20:22 UTC, merged