Add workflow bundle test script
airplanedev/lib pull request #370
Opened 2022-10-27 15:32 UTC by yolken-airplane

## Description
This change updates the workflow build process to run a special tester script to check for Node.js import errors. The tester script runs a workflow replay and checks the logs for failures related to calling forbidden methods; if the script fails, the build fails with a message that should allow users to understand what's going on and fix their code accordingly.

## Test plan
Testing completed via running some builds locally. In the "good" case, the outputs look like:

```
⣯ ---> b703a91795b7
Step 19/21 : RUN node /airplane/.airplane/test-bundle.js
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in a4588cb86c67
⣯[INFO] [temporal_sdk_core] Registering replay worker task_queue="__airplaneEntrypoint-0"
[INFO] [temporal_sdk_core::worker] Initializing worker task_queue=__airplaneEntrypoint-0
[INFO] Worker state changed {"state":"RUNNING"}
[WARN] No activities registered, not polling for activity tasks
⡿{}
[INFO] [temporal_sdk_core::worker] Initiated shutdown
[INFO] [temporal_sdk_core::worker::workflow::workflow_stream] Workflow shutdown is done
⣟[INFO] Worker state changed {"state":"DRAINED"}
[INFO] Worker state changed {"state":"STOPPED"}
⡿ ---> a6837c512243
```

In the "bad" case, the outputs look like:

```
---> Running in b782282f886f
⣾[INFO] [temporal_sdk_core] Registering replay worker task_queue="__airplaneEntrypoint-0"
[INFO] [temporal_sdk_core::worker] Initializing worker task_queue=__airplaneEntrypoint-0
[INFO] Worker state changed {"state":"RUNNING"}
[WARN] No activities registered, not polling for activity tasks
⣟[ERROR] Failed to activate workflow {"runId":"bc761765-7fca-4d3e-89ff-0fa49379dc7a","error":{},"workflowExists":false}
[WARN] [temporal_sdk_core::worker::workflow] Failing workflow task run_id=bc761765-7fca-4d3e-89ff-0fa49379dc7a failure=Failure { failure: Some(Failure { message: "Workflows do not have access to Node.js built-in packages (cannot access \"stream.PassThrough\"). Move that logic into a Node.js task and call the task from your workflow.", source: "TypeScriptSDK", stack_trace: "Error: Workflows do not have access to Node.js built-in packages (cannot access \"stream.PassThrough\"). Move that logic into a Node.js task and call the task from your workflow.\n    at getError (/airplane/.airplane/shims-stream.js:2:0)\n    at Object.get (/airplane/.airplane/shims-stream.js:17:0)\n    at ../../node_modules/nodemailer/lib/fetch/index.js (/airplane/node_modules/nodemailer/lib/fetch/index.js:7:20)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/shared/index.js (/airplane/node_modules/nodemailer/lib/shared/index.js:8:16)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/mailer/index.js (/airplane/node_modules/nodemailer/lib/mailer/index.js:4:15)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/nodemailer.js (/airplane/node_modules/nodemailer/lib/nodemailer.js:3:15)\n    at __webpack_require__ (webpack/bootstrap:19:0)", encoded_attributes: None, cause: None, failure_info: None }) }
[INFO] [temporal_sdk_core::worker] Initiated shutdown
[INFO] [temporal_sdk_core::worker::workflow::workflow_stream] Workflow shutdown is done
[INFO] Worker state changed {"state":"DRAINED"}
[INFO] Worker state changed {"state":"STOPPED"}
Unhandled rejection { runId: undefined } Error: Error testing workflow bundle: failure=Failure { failure: Some(Failure { message: "Workflows do not have access to Node.js built-in packages (cannot access \"stream.PassThrough\"). Move that logic into a Node.js task and call the task from your workflow.", source: "TypeScriptSDK", stack_trace: "Error: Workflows do not have access to Node.js built-in packages (cannot access \"stream.PassThrough\"). Move that logic into a Node.js task and call the task from your workflow.\n    at getError (/airplane/.airplane/shims-stream.js:2:0)\n    at Object.get (/airplane/.airplane/shims-stream.js:17:0)\n    at ../../node_modules/nodemailer/lib/fetch/index.js (/airplane/node_modules/nodemailer/lib/fetch/index.js:7:20)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/shared/index.js (/airplane/node_modules/nodemailer/lib/shared/index.js:8:16)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/mailer/index.js (/airplane/node_modules/nodemailer/lib/mailer/index.js:4:15)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/nodemailer.js (/airplane/node_modules/nodemailer/lib/nodemailer.js:3:15)\n    at __webpack_require__ (webpack/bootstrap:19:0)", encoded_attributes: None, cause: None, failure_info: None }) }
    at /airplane/.airplane/test-bundle.js:112:13
    at Array.forEach (<anonymous>)
    at testBundle (/airplane/.airplane/test-bundle.js:106:14)

Error: The command '/bin/sh -c node /airplane/.airplane/test-bundle.js' returned a non-zero code: 1
```

2022-10-28 14:49 UTC, colinking requested changes

2022-10-28 14:49 UTC, colinking commented on pkg/examples/javascript/workflowbadimport/package.json
> +    "airplane": "0.2.9",
bump to the latest

2022-10-28 14:49 UTC, colinking commented on pkg/build/node.go
> +		RUN node /airplane/.airplane/test-bundle.js
Can we merge this into `workflow-bundler.js` and run it just directly after creating the bundle? One less layer to cache.

2022-10-28 14:49 UTC, colinking commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
One idea for reducing noise: what if we aggregate these logs in-memory and then only log them if we detect an error? In the happy path, there won't be any new build logs.

2022-10-28 14:49 UTC, colinking commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
Could we best-effort parse the error log to format it more nicely? I'm worried that this error message looks too much like an "internal" error and users may not read far enough to realize it's a bug with their code.

Before

```
Unhandled rejection { runId: undefined } Error: Error testing workflow bundle: failure=Failure { failure: Some(Failure { message: "Workflows do not have access to Node.js built-in packages (cannot access \"stream.PassThrough\"). Move that logic into a Node.js task and call the task from your workflow.", source: "TypeScriptSDK", stack_trace: "Error: Workflows do not have access to Node.js built-in packages (cannot access \"stream.PassThrough\"). Move that logic into a Node.js task and call the task from your workflow.\n    at getError (/airplane/.airplane/shims-stream.js:2:0)\n    at Object.get (/airplane/.airplane/shims-stream.js:17:0)\n    at ../../node_modules/nodemailer/lib/fetch/index.js (/airplane/node_modules/nodemailer/lib/fetch/index.js:7:20)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/shared/index.js (/airplane/node_modules/nodemailer/lib/shared/index.js:8:16)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/mailer/index.js (/airplane/node_modules/nodemailer/lib/mailer/index.js:4:15)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/nodemailer.js (/airplane/node_modules/nodemailer/lib/nodemailer.js:3:15)\n    at __webpack_require__ (webpack/bootstrap:19:0)", encoded_attributes: None, cause: None, failure_info: None }) }
    at /airplane/.airplane/test-bundle.js:112:13
    at Array.forEach (<anonymous>)
    at testBundle (/airplane/.airplane/test-bundle.js:106:14)
```

After (ideally just the error message -- the stack trace doesn't seem helpful)

```
Workflows do not have access to Node.js built-in packages (cannot access "stream.PassThrough"). Move that logic into a Node.js task and call the task from your workflow.
```

2022-10-28 14:53 UTC, yolken-airplane commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
I think the stack trace is helpful? Otherwise, users might not understand where the bad call is happening- in this case, `stream.PassThrough` is buried deep within the `nodemailer` library.

2022-10-28 14:55 UTC, yolken-airplane commented on pkg/build/node.go
> +		RUN node /airplane/.airplane/test-bundle.js
Sure, let me give that a try.

2022-10-28 14:55 UTC, yolken-airplane commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
Can we defer this a bit? I'm kind of worried that we're not catching all the errors now, so if we hide them then it may be hard to debug cases where the build is ok but then users hit another kind of error when they run their workflows.

2022-10-28 14:59 UTC, yolken-airplane commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
At the least, let me see if I can make the error a little prettier- the `Unhandled rejection` thing is a little jarring.

2022-10-28 15:11 UTC, colinking commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
Ah, I missed the reference to `nodemailer` in the stack trace. Let's keep the stack trace then!

2022-10-28 21:21 UTC, yolken-airplane commented on pkg/build/node.go
> +		RUN node /airplane/.airplane/test-bundle.js
Done!

2022-10-28 21:23 UTC, yolken-airplane commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
Cleaned up the error message a bit to remove the "Unhandled rejection" part. It now looks like:

```
Error: Error testing workflow bundle: failure=Failure { failure: Some(Failure { message: "Workflows do not have access to Node.js built-in packages (cannot access \"stream.PassThrough\"). Move that logic into a Node.js task and call the task from your workflow.", source: "TypeScriptSDK", stack_trace: "Error: Workflows do not have access to Node.js built-in packages (cannot access \"stream.PassThrough\"). Move that logic into a Node.js task and call the task from your workflow.\n    at getError (/airplane/.airplane/shims-stream.js:2:0)\n    at Object.get (/airplane/.airplane/shims-stream.js:17:0)\n    at ../../node_modules/nodemailer/lib/fetch/index.js (/airplane/node_modules/nodemailer/lib/fetch/index.js:7:20)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/shared/index.js (/airplane/node_modules/nodemailer/lib/shared/index.js:8:16)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/mailer/index.js (/airplane/node_modules/nodemailer/lib/mailer/index.js:4:15)\n    at __webpack_require__ (webpack/bootstrap:19:0)\n    at ../../node_modules/nodemailer/lib/nodemailer.js (/airplane/node_modules/nodemailer/lib/nodemailer.js:3:15)\n    at __webpack_require__ (webpack/bootstrap:19:0)", encoded_attributes: None, cause: None, failure_info: None }) }
    at /airplane/.airplane/workflow-bundler.js:205:13
    at Array.forEach (<anonymous>)
    at testBundle (/airplane/.airplane/workflow-bundler.js:199:14)
    at async main (/airplane/.airplane/workflow-bundler.js:227:5)
```

2022-10-28 21:25 UTC, yolken-airplane commented on pkg/examples/javascript/workflowbadimport/package.json
> +    "airplane": "0.2.9",
Done.

2022-10-31 20:15 UTC, colinking commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
That's still not too great. For example, the stack trace that's shown isn't the useful one. Can we extract the `stack_trace` field and show that instead?

2022-10-31 20:18 UTC, colinking approved these changes
LGTM apart from the error message 😇

2022-11-01 01:37 UTC, yolken-airplane commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
Yeah, let me give this a try. And, if we can't parse it out, we can just default to the current format.

2022-11-01 14:11 UTC, yolken-airplane commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
Ok, I think I got a better error message here:

```
Error: testing workflow bundle: Error: Workflows do not have access to Node.js built-in packages (cannot access \"stream.PassThrough\"). Move that logic into a Node.js task and call the task from your workflow.
    at getError (/airplane/.airplane/shims-stream.js:2:0)
    at Object.get (/airplane/.airplane/shims-stream.js:17:0)
    at ../../node_modules/nodemailer/lib/fetch/index.js (/airplane/node_modules/nodemailer/lib/fetch/index.js:7:20)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at ../../node_modules/nodemailer/lib/shared/index.js (/airplane/node_modules/nodemailer/lib/shared/index.js:8:16)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at ../../node_modules/nodemailer/lib/mailer/index.js (/airplane/node_modules/nodemailer/lib/mailer/index.js:4:15)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at ../../node_modules/nodemailer/lib/nodemailer.js (/airplane/node_modules/nodemailer/lib/nodemailer.js:3:15)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at /airplane/.airplane/workflow-bundler.js:207:15
    at Array.forEach (<anonymous>)
    at testBundle (/airplane/.airplane/workflow-bundler.js:199:14)
    at async main (/airplane/.airplane/workflow-bundler.js:237:5)

Error: The command '/bin/sh -c node /airplane/.airplane/workflow-bundler.js' returned a non-zero code: 1
```

2022-11-01 14:12 UTC, yolken-airplane commented on pkg/build/workflow/test-bundle.js
> +      throw new Error(`Error testing workflow bundle: ${value.substring(failureIndex)}`);
It was a pain because of all the newline escaping that's done as part of our embedded script conversion logic.

2022-11-01 14:20 UTC, merged