Implement bundle shell build
airplanedev/lib pull request #392
Opened 2022-11-04 19:45 UTC by leeweisberger

## Description

Implement shell bundle build.

To support `COPY --chmod` I switched us to using buildkit for builds (which we are using in the backend anyways so it's good to have parity).

## Test plan
Same unit tests as regular shell passes + a bunch of shell scripts bundled together.

2022-11-04 19:46 UTC, leeweisberger commented on pkg/build/bundle_builder.go
> +		var msg *dockerJSONMessage.JSONMessage
There is a better way to do this log displaying most likely. I spent most of my day trying to figure this out. This version is good enough imo for something that is mostly used in tests

2022-11-04 19:46 UTC, leeweisberger commented on pkg/build/shell.go
> +		COPY --chmod=700 . .
Nice and simple!

2022-11-04 19:47 UTC, leeweisberger commented on pkg/build/universal-node-shim.js
> +    console.log(
I just formatted this file

2022-11-04 19:47 UTC, leeweisberger commented on pkg/build/universal-node-shim.js
> +  const params = process.argv[4];
And made these variables

2022-11-04 20:38 UTC, ameyakhare requested changes

2022-11-04 20:38 UTC, ameyakhare commented on pkg/build/builder_test.go
> +			c.Entrypoint = append(c.Entrypoint, fmt.Sprintf("%s=%s", k, v))
umm I only think this works for bash, so you need to make this work for both

2022-11-04 20:38 UTC, ameyakhare commented on pkg/build/builder_test.go
> +	fmt.Println(string(logs))
remove

2022-11-07 16:30 UTC, ameyakhare approved these changes

2022-11-07 16:46 UTC, merged