Support inline tasks in views
airplanedev/lib pull request #433
Opened 2022-11-30 22:21 UTC by leeweisberger

## Description
Currently you can't define an inline task in a view because executing the task in a node environment fails with browser-specific concepts that are pulled in by the view.

I fixed this for discovery by replacing the document with JSDOM.

We have to do the same thing when builiding locally and remotely.

In order to use esbuild with JSDOM we have to use a simple plugin. In order to use a plugin we have to call esbuild's JS API rather than using the CLI or the go api. I've wanted to switch to this anyway so we can use plugins.

I switched local building to use the new universal shim so that it's more similar to the real prod build

## Test plan
I moved over the whole suite of unit test -> bundle building. I also added tests for the local dev bit.

2022-11-30 22:25 UTC, leeweisberger commented on pkg/build/esbuild.js
> +const esbuild = require("esbuild");
This is our new esbuild builder

2022-11-30 22:27 UTC, leeweisberger commented on pkg/build/node.go
> -		# qemu (on m1 at least) segfaults while looking up a UID/GID for running
We're installing this in the shim

2022-11-30 22:50 UTC, leeweisberger commented on pkg/runtime/javascript/javascript.go
> +	shim := build.UniversalNodeShim
We're using the universal shim now. I didn't have to do this, but we might as well use the same shim in local / remote

2022-11-30 22:51 UTC, leeweisberger commented on pkg/runtime/javascript/javascript.go
> +	return []string{"node", filepath.Join(taskDir, "dist", "shim.js"), filepath.Join(taskDir, "dist", entrypointJS), entrypointFunc, string(pv)}, closer, nil
Now this is more consistent with how tasks are executed in the bundle build world

2022-11-30 22:52 UTC, leeweisberger commented on pkg/build/node_test.go
> +		{
I ported all hte tests over from the non-bundle-build test suite

2022-12-01 21:44 UTC, calufornia reviewed
Runtime changes mostly look good to me, a couple comments

2022-12-01 21:44 UTC, calufornia commented on pkg/build/node.go
> +			flags = append(flags, `"@temporalio"`, `"--external:@swc"`)
How come we still mark `swc` as external?

2022-12-01 21:44 UTC, calufornia commented on pkg/runtime/javascript/javascript.go
> +		fmt.Sprintf(`["%s"]`, strings.Join(external, ", ")),
This shouldn't be quoted, right? Since the external deps are already quoted so it would end up being `[""a", "b""]`

2022-12-01 21:44 UTC, calufornia commented on pkg/runtime/javascript/javascript.go
> +		fmt.Sprintf(`["%s"]`, strings.Join(external, ", ")),
Same here

2022-12-01 21:44 UTC, calufornia commented on pkg/runtime/javascript/javascript.go
> +	logger.Debug("Built JS in %s", time.Since(start).String())
Do you know how much longer/shorter it takes to prepare the run using the universal node shim?

2022-12-02 20:39 UTC, leeweisberger commented on pkg/runtime/javascript/javascript.go
> +	logger.Debug("Built JS in %s", time.Since(start).String())
I didn't measure. But the universal shim doesn't add anything that would add latency except that the shim has to be bundled which should be very quick

2022-12-02 20:44 UTC, calufornia approved these changes

2022-12-05 22:00 UTC, ameyakhare requested changes
leave this one out for tomorrow

2023-01-03 16:01 UTC, leeweisberger commented
Closing in favor of smaller prs

2023-01-03 16:01 UTC, closed without merging