Optimize local javascript task execution
airplanedev/lib pull request #557
Opened 2023-02-22 05:04 UTC by calufornia

## Description

Speeds up local execution of JS+TS tasks by optimizing how we build local JS tasks. Because shim dependencies and the shim itself should not change between runs (or tasks), we don't attempt to install shim dependencies or build the shim if they already exist.

However, if our build script (`esbuild.js`) or any of the build dependencies change, we want to rebuild the shim. To detect this case, we track a dependency hash file `dep-hash` the detects whether or not either of these has changed since the last run, and if so we rebuild the shim. This is similar to how we force `Vite` to regenerate its dependency cache. (https://github.com/airplanedev/cli/pull/886).

Note that `npm install` does not reinstall dependencies if they're already installed, but I've found that this check requires ~1s. Checking the dependency hash to see if we need to reinstall is much quicker.

Also adds more debug logs to see where JS task execution might be bottle-necked. 

Also writes the built entrypoint to an individual run subdirectory instead of the task subdirectory—we were seeing some occasional race conditions where one run was causing the deletion of the task directory while another run was occurring, causing the second run to error. We now keep a task subdirectory around (similar to how we keep a view subdirectory in `.airplane-view`, and cleanup run subdirectories on the fly.

After these changes, the `.airplane/` directory looks like the following:
```
.airplane/
|_dep-hash
|_esbuild.js
|_node_modules
|_package.json
|_package-lock.json
|_my_task
   |_run1234
      |_{entrypoint}
   |_run2345
      |_{entrypoint}
```

## Test plan
Tested local JS execution and verified that run preparation time (after the 1st for a task across all Studio sessions) went from 3-7s to 0.4-0.8 seconds.

2023-02-22 05:08 UTC, calufornia commented on pkg/build/node.go
> +func GenShimPackageJSON(rootDir string, packageJSONs []string, isWorkflow, isBundle, fallbackToUserDeps bool) ([]byte, error) {
@leeweisberger I noticed that checking the `package.json` files for build dependencies (e.g `getLockPackageVersion`) takes a significant amount of time (~1.5s total). I don't think we need to override build deps with user deps, and is something I think we wanted to remove regardless. I added `fallbackToUserDeps` for backwards compatibility (it's `true` everywhere except when building locally now), but if we want we can just remove that logic altogether.

2023-02-22 21:51 UTC, leeweisberger requested changes
Good stuff.

Just blocking on the logic for building / using cached versions of the build deps/shim

2023-02-22 21:51 UTC, leeweisberger commented on pkg/build/node.go
> +	pjson, err := GenShimPackageJSON(root, packageJSONs, isWorkflow, false, true)
I know it's annoying, but can we move these into a config object? Too many params to keep track of

2023-02-22 21:51 UTC, leeweisberger commented on pkg/build/node.go
> +func GenShimPackageJSON(rootDir string, packageJSONs []string, isWorkflow, isBundle, fallbackToUserDeps bool) ([]byte, error) {
sgtm. Can you leave a todo to resolve this? I think I have a task to resolve it in a couple of cycles

2023-02-22 21:51 UTC, leeweisberger commented on pkg/build/node_externals.go
> +		"Error getting %q version from yarn: %v\n",
I know you kind of removed this, but why are we printing this out? I feel like it is internal and shouldn't be logged?

2023-02-22 21:51 UTC, leeweisberger commented on pkg/runtime/javascript/javascript.go
> +	airplaneDir, taskDir, _, err := airplane_directory.CreateTaskDir(root, opts.TaskSlug)
This is the part you referred to in the description where we are keeping this around?

2023-02-22 21:51 UTC, leeweisberger commented on pkg/runtime/javascript/javascript.go
> +	depsChanged, err := CheckDepHash(airplaneDir)
Can you call this like `buildDepsChanged` or something? Cause it isn't checking that user deps changed?

2023-02-22 21:51 UTC, leeweisberger commented on pkg/runtime/javascript/javascript.go
> +	if _, err := os.Stat(filepath.Join(airplaneDir, "node_modules")); (err == nil && !depsChanged) || errors.Is(err, os.ErrNotExist) {
why is this confusing me: You're saying if there is no node_modules reinstall (makes sense) OR if the deps haven't changed reinstall (doesn't make sense). Should it be if the deps have changed reinstall?

2023-02-22 21:51 UTC, leeweisberger commented on pkg/runtime/javascript/javascript.go
> +	if _, err := os.Stat(builtShimPath); (err == nil && !depsChanged) || errors.Is(err, os.ErrNotExist) {
same here

2023-02-23 06:35 UTC, calufornia commented on pkg/build/node_externals.go
> +		"Error getting %q version from yarn: %v\n",
Hmm yeah good point. Are you suggesting we remove the logs entirely? We don't use log.Printf anywhere else in lib. I suppose the right thing to do would be to thread down a logger

2023-02-23 06:38 UTC, calufornia commented on pkg/runtime/javascript/javascript.go
> +	airplaneDir, taskDir, _, err := airplane_directory.CreateTaskDir(root, opts.TaskSlug)
Correct— I think it's OK to leave for now (since it's inside a hidden folder, and I don't expect users to have too many tasks)

2023-02-23 06:54 UTC, calufornia commented on pkg/runtime/javascript/javascript.go
> +	if _, err := os.Stat(filepath.Join(airplaneDir, "node_modules")); (err == nil && !depsChanged) || errors.Is(err, os.ErrNotExist) {
Sorry, `depsChanged` was incorrectly named—`checkDepHash` returns whether or not the hashes are _equal_, not different. Updated the variable name to reflect this

2023-02-23 14:38 UTC, leeweisberger commented on pkg/build/node_externals.go
> +		"Error getting %q version from yarn: %v\n",
Yeah remove the log entirely

2023-02-23 14:39 UTC, leeweisberger approved these changes

2023-02-23 14:39 UTC, leeweisberger commented on pkg/build/node_externals.go
> +		"Error getting %q version from yarn: %v\n",
Yeah remove the log entirely

2023-02-23 16:49 UTC, merged