Add tracing functionality to lib
airplanedev/lib pull request #574
Opened 2023-03-02 00:14 UTC by yolken-airplane

## Description
This change adds some basic tracing functionality to lib so that we can use it in client-side lib and CLI code. It's adapted from the tracing library in the API, but has a few differences to account for the fact that it's running client-side:

1. The client hits an arbitrary collector (e.g., one of ours) instead of the honeycomb one
2. Things like the user, team, etc. are set at the resource level since these should all be known when the tracer is initialized
3. The otel `resource.WithProcess`, `resource.WithOS`, etc. helpers are used to automatically set a bunch of helpful fields based on the user's environment

Once this is in, I'll update the lib version in the cli and use this functionality to add some optional tracing in that tool.

## Test plan
Testing completed successfully via updating the lib version of the cli and adding some basic tracing functionality in `airplane dev`. 

Here's an example trace: https://ui.honeycomb.io/airplane/datasets/stage/result/cZa7ppqxEo5/trace/wssRNFyHTWD?fields[]=c_name&fields[]=c_service.name&span=d605fab95e33fa19

<img width="1431" alt="Screenshot 2023-03-01 at 7 13 35 PM" src="https://user-images.githubusercontent.com/102088763/222296506-ff14b2d7-ab57-4106-82be-37ebcd5748a0.png">

2023-03-02 00:15 UTC, yolken-airplane commented on .editorconfig
> +[*.{js,py,ts}]
@colinking has a fix for the golang formatting here, I'll revert this once that's in.

2023-03-02 20:56 UTC, leeweisberger requested changes
Can airport use this as well?

2023-03-02 20:56 UTC, leeweisberger commented on pkg/utils/tracing/tracing.go
> +			attribute.String("cli_version", opts.Version),
Can airport take advantage of this (it also imports lib)? Does it just leave this one blank? What about the service name?

2023-03-03 00:15 UTC, yolken-airplane commented
> Can airport use this as well?

Possibly. There are few significant differences, including the tracer initialization and also the `getDefaultSpanFields` field- in the airport case, it calls some airport-specific functionality to set the user and team. 

Let me think about this some more. If we can get around the `getDefaultSpanFields` issue, then maybe we can take the tracer initialization out of here and just have each app do its own initialization.

2023-03-03 00:17 UTC, yolken-airplane commented
Actually, I think we can use the baggage to set the authn stuff in airport. Let me see if that works...

2023-03-06 18:00 UTC, yolken-airplane commented
> > Can airport use this as well?
> 
> Possibly. There are few significant differences, including the tracer initialization and also the `getDefaultSpanFields` field- in the airport case, it calls some airport-specific functionality to set the user and team.
> 
> Let me think about this some more. If we can get around the `getDefaultSpanFields` issue, then maybe we can take the tracer initialization out of here and just have each app do its own initialization.

Ok, I've done some cleanups so that this library can be used in airport too. We can use the baggage-related functionality to get around not having access to the airport authn libraries in `getDefaultSpanFields`.

@leeweisberger can you take another look when you get a chance?

2023-03-06 20:51 UTC, leeweisberger approved these changes

2023-03-06 21:18 UTC, merged