Add event listeners for errors and unhandledrejections to send messages to parent frame
airplanedev/lib pull request #579
Opened 2023-03-02 21:16 UTC by rose-huang

## Description
We add event listeners when we get an error event or unhandledrejection event in the view

We duplicate some code here that we have in the views lib (ViewMessage and sendViewMessage) but this seems better than trying to export those out of views and having to deal with backward compatibility issues

## Test plan
Testing alongside views and web changes

2023-03-02 23:42 UTC, leeweisberger requested changes

2023-03-02 23:42 UTC, leeweisberger commented on pkg/build/views/main.tsx
> +      time: dayjs().unix(),
Same here. No dayjs

2023-03-02 23:42 UTC, leeweisberger commented on pkg/build/views/package.json
> +    "object-hash": "3.0.0",
This doesn't actually provide this dependency, it's just a place where we track dependency types. We need to update the view build to ensure that object-hash is installed.

Look up GenViewsShimPackageJSON. You need to add the object-hash there.

 Also update renovate.json so that we don't update this dependency often

2023-03-03 16:26 UTC, rose-huang commented on pkg/build/views/package.json
> +    "object-hash": "3.0.0",
I still keep this here right? in addition to adding to `GenViewsShimPackageJSON`?

2023-03-03 16:32 UTC, leeweisberger approved these changes

2023-03-03 16:32 UTC, leeweisberger commented on pkg/build/views/package.json
> +    "object-hash": "3.0.0"
Yup we still keep this here. It helps us keep these deps up to date because renovate automatically looks at package.json files and updates them, That's the only reason we're using a package.json

2023-03-06 21:46 UTC, merged