Add comments to generated YAML file
airplanedev/lib pull request #68
Opened 2022-02-25 21:42 UTC by francescaleung

There needs to be another pass for copy, but this pass is for the generation part. It's somewhat ugly & the end result is less than ideal, but short of switching libraries (again!) this might be the best we could do.

Resolves AIR-3174.

2022-02-28 17:22 UTC, leeweisberger requested changes
Would like to hear some thoughts on a better way to maintain this than adding new function calls

And tests please

2022-02-28 17:22 UTC, leeweisberger commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +		// Add an empty line, then break the text into lines of max 78 characters.
So we need a newline before each comment? Does it look like
```
#
# mycomment
```

That's pretty crummy...

2022-02-28 17:22 UTC, leeweisberger commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +	})
Can we create a yaml file with these comments? One place where we can update them?

Or better yet it would be great if we could just pull these from the json schema - is that something we would do? We have the text and example in the json schema and we just run through that and create comments from it.

Might be tough with the doAdd stuff since that is dynamic... what do you think the best way to maintain this is?

2022-02-28 17:22 UTC, leeweisberger commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +func (d Definition_0_3) getCommentMap() (yaml.CommentMap, []byte, error) {
Is there a way we can test this? It's gonna be kind of tough to make changes here and not break things... I want a golden file of what we expect the defn to look like with comments and then ensure that we produce exactly that.

2022-03-02 23:31 UTC, francescaleung commented
Superseded by https://github.com/airplanedev/lib/pull/77.

2022-03-02 23:31 UTC, closed without merging