Support deploying tasks to new environments
airplanedev/lib pull request #75
Opened 2022-03-01 19:53 UTC by colinking

2022-03-03 16:56 UTC, francescaleung requested changes
Mostly okay, but the interpolation assumption for definition files is incorrect.

Also I think @leeweisberger should get looped in for the discoverer changes.

2022-03-03 16:56 UTC, francescaleung commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +			DisallowSelfApprove: pointers.Bool(false),
I'd rather drop this, default nil seems safer

2022-03-03 16:56 UTC, francescaleung commented on pkg/deploy/taskdir/definitions/interface.go
> +	GetName() string
What's this for?

2022-03-03 16:56 UTC, francescaleung commented on pkg/runtime/comment.go
> +func Slug(filePath string) string {
I rather liked the explicit `ok` return value, but up to you

2022-03-03 16:56 UTC, francescaleung commented on pkg/utils/pointers/pointers.go
> +package pointers
yea, this is probably overdue

2022-03-03 16:56 UTC, francescaleung commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +		disallow := !*d.AllowSelfApprovals
maybe we need a pointers.ToBool, would make this easier to read

2022-03-03 16:56 UTC, francescaleung commented on pkg/deploy/discover/script_discover.go
> +		return nil, nil
So we're not logging that we've found a valid file but it won't deploy because the task doesn't exist? if the task isn't in the environment, do we still fall into this case?

2022-03-03 16:56 UTC, francescaleung commented on pkg/deploy/discover/defn_discover.go
> +		TaskInterpolationMode: "jst",
False! Not guaranteed. True in 99% of cases, probably.

2022-03-03 17:46 UTC, colinking commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +			DisallowSelfApprove: pointers.Bool(false),
So if you have this in a task YAML:

```yaml
allowSelfApprove: false
```

And then you remove that and re-deploy, wouldn't you expect that to clear to some default value?

2022-03-03 17:47 UTC, colinking commented on pkg/deploy/taskdir/definitions/interface.go
> +	GetName() string
https://github.com/airplanedev/cli/pull/412/files#diff-c80696cdcbfd2853cf9e9c0054a1bee04de602ac383c0b678af62504dc13b90fR186

2022-03-03 17:50 UTC, colinking commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +		disallow := !*d.AllowSelfApprovals
Maybe a `pointers.NegateBool(d.AllowSelfApprovals)`? A `ToBool` on its own wouldn't help much here. Going to punt on this.

2022-03-03 21:27 UTC, colinking commented on pkg/deploy/discover/script_discover.go
> +		return nil, nil
Good catch. I didn't mean to remove the log. I'll bring that back.

If a task doesn't exist in an environment, we would currently not deploy it. I'll open a ticket to discuss supporting that (e.g. we could copy the config from another environment).

2022-03-03 22:12 UTC, colinking commented on pkg/deploy/discover/script_discover.go
> +		return nil, nil
@francescaleung brought the log message back!

2022-03-04 15:28 UTC, francescaleung approved these changes

2022-03-04 15:28 UTC, francescaleung commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +			DisallowSelfApprove: pointers.Bool(false),
Ahh okay, I'd rather this bit get looped into the AllowSelfApprovals bit on line 833 then.

2022-03-04 15:31 UTC, francescaleung commented on pkg/deploy/discover/script_discover.go
> +	})
If a task doesn't exist in this environment, does that mean you can't deploy-via-script?

2022-03-04 16:21 UTC, leeweisberger commented
I walked through this, but there's way too much going on into this pr to keep track of everything. I can't really confidently review this. Up to @francescaleung whether she's confident in the review here

2022-03-04 16:25 UTC, colinking commented on pkg/deploy/discover/script_discover.go
> +	})
For now, no. There's a ticket for that: https://linear.app/airplane/issue/AIR-3223/deploy-code-only-tasks-to-new-environments

2022-03-04 16:42 UTC, merged