Add GenerateCommentedFile to (sometimes) generate a commented YAML file
airplanedev/lib pull request #77
Opened 2022-03-02 23:25 UTC by francescaleung

Needs tests.

Resolves AIR-3174, AIR-2490.

---
cc @joshma

2022-03-02 23:30 UTC, joshma commented
maybe add tests that the generated yaml is valid yaml?

2022-03-03 20:45 UTC, leeweisberger requested changes
Approach looks good. Question about determing whether a yaml file is new. Also need tests before approving

2022-03-03 20:45 UTC, leeweisberger commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +		return d.Marshal(format)
Rather than calculate this, shouldn't we know whether a task yaml already has stuff when we call this function? We should have a path where we are creating a defn from scratch and one where we are creating it from a pre-existing task. Can we pass a bool into this function with whether the task has already been initialized?

2022-03-03 20:45 UTC, leeweisberger commented on pkg/deploy/taskdir/definitions/yaml_templates.go
> +const definitionTemplate = `
Can we add tests that fill in templated values and then validate that these are valid? I think that's pretty important before merging.

2022-03-03 22:47 UTC, francescaleung commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +		return d.Marshal(format)
You're suggesting that the caller should determine whether the commented YAML can be generated? That seems more dicey than this calculation, & this calculation is already pretty dicey... I can have a bool somewhere indicating whether the def was initialized via NewDefinition or NewDefinitionFromTask, but since all fields are public anyway, callers technically have the ability to tweak things outside of Definition methods. It wouldn't be ideal, but it's technically possible.

2022-03-03 22:48 UTC, leeweisberger commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +		return d.Marshal(format)
Don't we know at some point whether we have a previously existing task or this is brand new? And isn't that the only information we need?

2022-03-03 22:49 UTC, leeweisberger commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +		return d.Marshal(format)
I guess the task might be previously existing but have none of this information, in which case we want to add the comments... so I think I'm wrong

2022-03-04 20:40 UTC, leeweisberger approved these changes

2022-03-04 20:41 UTC, merged