Add TransactionMode to SQL tasks
airplanedev/lib pull request #98
Opened 2022-03-24 15:26 UTC by francescaleung

## Description

New SQL tasks get created with a default TransactionMode of auto. Initializing SQL tasks without a TransactionMode results in no transactionMode entry in the definition file. Resolves AIR-2896.

## Test plan

Deploy a SQL task with a transaction mode. Initialize a SQL task from an existing task with a transaction mode, and without a transaction mode.

2022-03-24 15:29 UTC, francescaleung commented
Blocked on AIR-3395.

2022-03-25 18:17 UTC, colinking requested changes
Have some thoughts on how we handle default values here. Can chat more over Slack if that's faster.

2022-03-25 18:17 UTC, colinking commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +			TransactionMode: "auto",
What do you think of not writing this field if `auto` when initializing a SQL task? And then we treat "not set" as "auto".

Ideally these YAML files are as minimal as possible.

2022-03-25 18:17 UTC, colinking commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +	}
If so, then we'd default this to `auto` here if not set.

2022-03-25 18:17 UTC, colinking commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +	}
And then the API would fallback on the task's current value (else auto) if it gets no value for the transaction mode.

2022-03-25 18:17 UTC, colinking commented on pkg/deploy/taskdir/definitions/fixtures/sql.task.yaml
> +  transactionMode: auto
In this case, we would also comment this out like the other optional fields:

```suggestion
  # transactionMode: auto
```

2022-03-25 18:17 UTC, colinking commented on pkg/deploy/taskdir/definitions/yaml_templates.go
> +  transactionMode: {{.TransactionMode}}
And this would be gated behind whether `.TransactionMode` is non-empty.

2022-03-28 21:41 UTC, colinking approved these changes

2022-03-28 21:41 UTC, colinking commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +var _ yaml.IsZeroer = SQLTransactionMode("")
Checking IIUC; this logic is only needed for initializing a YAML from a task, since we init a `SQLDefinition_0_3` then serialize it as YAML?

2022-03-29 14:50 UTC, francescaleung commented on pkg/deploy/taskdir/definitions/def_0_3.go
> +var _ yaml.IsZeroer = SQLTransactionMode("")
This logic is needed to tell the yaml serializer that `TransactionMode=auto` should not be written out. In practice this is only for existing tasks that are initialized; for brand new tasks, we use our yaml template instead.

2022-03-31 22:22 UTC, merged